name: Checkout-test
on: 
  workflow_dispatch:
jobs:
  clone-repos:
    name: clone another repos
    runs-on: 
      labels: other-runner
    # strategy:
    #   matrix:
    #     maven: [ '3.9.6' ]
    steps:
      - name: Set up Maven Action
        uses: s4u/setup-maven-action@v1.12.0
      - uses: actions/checkout@v4
        with:
          repository: Mark-Zagob/test01
          ref: maven-test
      - name: check location
        run: pwd && ls -la
      - name: run maven build
        run: mvn install
      - name: list all file
        run: ls -la