name: Checkout-test
on: 
  workflow_dispatch:
jobs:
  clone-repos:
    name: clone another repos
    runs-on: 
      labels: test01
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Mark-Zagob/multibranch
          ref: branch111
      - name: check location
        run: pwd && ls -la