name: Checkout-test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      labels: python-runner

      steps:
      - name: Check out other repos
        uses: actions/checkout@v4
        with:
          repository: Mark-Zagob/multibranch
          ref: branch111

      - name: check location
        run: pwd && ls -la