name: Terraform Workflow

on:
  # Trigger on manual workflow dispatch
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run (prep or qa)"
        required: true
        default: "prep"

jobs:
  terraform:
    runs-on:
      labels: arc-runner-001

    steps:
      # Step 1: Checkout the code
      - name: Checkout terraform repository
        uses: actions/checkout@v4
        with:
          name: Mark-Zagob/samples-tf-aws
          ref: "main"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3


      # Step 2: Set environment variable based on input or branch
      - name: Set Environment
        id: set-env
        run: |
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV


      # Step 3: Configure Terraform environment (e.g., credentials)
      - name: Set Terraform Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials set."

      # Step 4: Initialize Terraform in the specific environment
      - name: Terraform Init
        working-directory: live/${{ env.environment }}
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: live/${{ env.environment }}
        run: terraform plan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        working-directory: live/${{ env.environment }}
        run: terraform apply --auto-approve
