name: Terraform With Cache

on:
  # Trigger on manual workflow dispatch
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run (prep or qa)"
        required: true
        default: "prep"

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  terraform:
    runs-on:
      labels: arc-runner-001

    steps:
      # Step 1: Checkout the code

      # - name: Checkout main repository
      #   uses: actions/checkout@v4

      - name: Checkout terraform repository
        uses: actions/checkout@v4
        with:
          repository: Mark-Zagob/samples-tf-aws
          ref: main
          #path: terraform_codes

      # setup nodejs
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # setup terraform  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5


      # Step 2: Set environment variable based on input or branch
      - name: Set Environment
        id: set-env
        run: |
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2


      # create terraform cache
      # - name: Create Terraform Plugin Cache Dir
      #   run: mkdir --parents $TF_PLUGIN_CACHE_DIR

      # - name: Cache Terraform
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.TF_PLUGIN_CACHE_DIR }}
      #     key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
      - uses: terraform-cache/terraform-cache@v1

      # Step 4: Initialize Terraform in the specific environment
      - name: Terraform Init
        working-directory: live/${{ env.environment }}
        run: terraform init


      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: live/${{ env.environment }}
        run: terraform plan
        # env:
        #   AWS_PROFILE: default
        #   AWS_REGION: ap-southeast-2
