name: wf public

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello

      - name: list file and location
        run: |
          ls -la
          pwd