name: wf public

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
        default: "/home"
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      # - name: Run a one-line script
      #   run: echo Hello

      - name: list file and location
        run: |
          lsb_release -a
      
      - name: workflow inputs
        run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Environment ${{ inputs.environment }}"
        if: ${{  github.event_name == 'workflow_dispatch'  }}
  
  second_job:
    runs-on: ubuntu-22.04
    needs: first_job
    steps:
      - name: check os version
        run: |
          lsb_release -a
          echo Job: ${{ github.job }}
      - name: run shell python
        shell: python {0}
        run: |
          import os
          x = "Dung"
          print(f'Hello {x} to gh action')
          print("Current directory:", os.getcwd())
          print("::set-output name=myOutput::Hello from Python")

  thirst_job:
    uses: ./.github/workflows/reuse-workflow.yaml
    needs: first_job